spring.application.name=rutinafit_backend
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.initialization-fail-timeout=60000

# Inicializar datos fijos
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# Limitar conexiones máximas del servidor
server.tomcat.max-connections= 1000
# Cierra la conexión si no hay actividad en 20 segundos
#server.tomcat.connection-timeout=20000 

server.port=8080
# Configuración de seguridad https
# server.port=8443
# server.ssl.enabled=true
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=pestillo
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=tomcat

# keytool -genkeypair -alias tomcat -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore keystore.p12 -validity 3650

# Configuración de email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_HOST_USER}
spring.mail.password=${EMAIL_HOST_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.url-front=${URL_FRONT:http://localhost:4200}
app.url-back=${URL_BACK:http://localhost:8080}
