spring.application.name=rutinafit_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/rutinafit_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Inicializar datos fijos
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# Limitar conexiones máximas del servidor
server.tomcat.max-connections= 1000

server.port=8080
# Configuración de seguridad https
# server.port=8443
# server.ssl.enabled=true
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=pestillo
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=tomcat

# keytool -genkeypair -alias tomcat -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore keystore.p12 -validity 3650