-- Insertar valores fijos en la tabla roles
--INSERT INTO roles (nombre) VALUES ('ADMINISTRADOR');
--INSERT INTO roles (nombre) VALUES ('NORMAL');
--INSERT INTO roles (nombre) VALUES ('ENTRENADOR');

-- Insertar valores fijos en la tabla premium
--INSERT INTO premium (nombre) VALUES ('GRATIS');
--INSERT INTO premium (nombre) VALUES ('TIER1');

-- ==========================================
-- 1. LIMPIEZA (BORRA TODO SI EXISTE)
-- ==========================================
DROP TABLE IF EXISTS amistades CASCADE;
DROP TABLE IF EXISTS solicitudes CASCADE;
DROP TABLE IF EXISTS ejercicios CASCADE;
DROP TABLE IF EXISTS ejercicio_info CASCADE;
DROP TABLE IF EXISTS sesiones CASCADE;
DROP TABLE IF EXISTS rutinas CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

-- ==========================================
-- 2. CREACIÓN DE TABLAS (SCHEMA)
-- ==========================================

-- Tabla Usuarios
CREATE TABLE usuarios (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(60) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    foto_perfil VARCHAR(255) DEFAULT NULL,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(255) NOT NULL,
    es_entrenador BOOLEAN DEFAULT FALSE,
    token VARCHAR(255) DEFAULT NULL UNIQUE,
    token_expiracion TIMESTAMP DEFAULT NULL,
    nivel_suscripcion VARCHAR(20) DEFAULT 'GRATIS', 
    entrenador_id BIGINT,
    CONSTRAINT fk_usuario_entrenador FOREIGN KEY (entrenador_id) REFERENCES usuarios(usuario_id)
);

-- Tabla Rutinas
CREATE TABLE rutinas (
    rutina_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL,
    foto_rutina VARCHAR(255) DEFAULT NULL,
    descripcion VARCHAR(255),
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_rutina_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(usuario_id)
);

-- Tabla Sesiones
CREATE TABLE sesiones (
    sesion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE,
    rutina_id BIGINT NOT NULL,
    CONSTRAINT fk_sesion_rutina FOREIGN KEY (rutina_id) REFERENCES rutinas(rutina_id)
);

-- Tabla Catálogo de Ejercicios (Info)
CREATE TABLE ejercicio_info (
    ejercicio_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo INTEGER NOT NULL, -- 1: Fuerza, 2: Cardio
    nombre VARCHAR(60) NOT NULL,
    descripcion VARCHAR(100),
    enlace_explicacion VARCHAR(255)
);

-- Tabla Ejercicios (Los realizados)
CREATE TABLE ejercicios (
    ejercicio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param1 DOUBLE PRECISION NOT NULL, -- Peso o Distancia
    param2 DOUBLE PRECISION NOT NULL, -- Reps o Tiempo
    sesion_id BIGINT NOT NULL,
    ejercicio_info_id BIGINT NOT NULL,
    CONSTRAINT fk_ejercicio_sesion FOREIGN KEY (sesion_id) REFERENCES sesiones(sesion_id),
    CONSTRAINT fk_ejercicio_info FOREIGN KEY (ejercicio_info_id) REFERENCES ejercicio_info(ejercicio_info_id)
);

-- Amistades
CREATE TABLE amistades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario1_id BIGINT NOT NULL,
    usuario2_id BIGINT NOT NULL,
    fecha_amistad TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_amistad_u1 FOREIGN KEY (usuario1_id) REFERENCES usuarios(usuario_id),
    CONSTRAINT fk_amistad_u2 FOREIGN KEY (usuario2_id) REFERENCES usuarios(usuario_id)
);

-- Solicitudes
CREATE TABLE solicitudes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remitente_id BIGINT NOT NULL,
    destinatario_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL, -- 'AMISTAD' o 'ENTRENAMIENTO'
    estado VARCHAR(20) NOT NULL, -- 'PENDIENTE', 'ACEPTADA', 'RECHAZADA'
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_solicitud_remitente FOREIGN KEY (remitente_id) REFERENCES usuarios(usuario_id),
    CONSTRAINT fk_solicitud_destinatario FOREIGN KEY (destinatario_id) REFERENCES usuarios(usuario_id)
);

-- =======================================================
-- 1. USUARIOS (Admin, Entrenador, Usuario)
-- =======================================================
-- NOTA: La contraseña es '123456' en texto plano. 
-- Si usas BCrypt en el backend, estos logins fallarán hasta que uses hashes reales.
INSERT INTO usuarios (username, email, password, rol, es_entrenador, nivel_suscripcion, entrenador_id, foto_perfil ) VALUES 
('admin', 'admin@correo.com', '$2a$10$dmkVr.E0jsbk5.rq0IxZAe/QdQPsTDXoy3DRo1StFdPB676e4Ve4S', 'ADMIN', 'FALSE', 'GRATIS', NULL, 'https://ui-avatars.com/api/?name=admin&background=random&color=fff&size=128'),
('entrenador', 'entrenador@correo.com', '$2a$10$dmkVr.E0jsbk5.rq0IxZAe/QdQPsTDXoy3DRo1StFdPB676e4Ve4S', 'ENTRENADOR', 'TRUE', 'GRATIS', NULL, 'https://ui-avatars.com/api/?name=entrenador&background=random&color=fff&size=128'),
('usuario', 'usuario@correo.com', '$2a$10$dmkVr.E0jsbk5.rq0IxZAe/QdQPsTDXoy3DRo1StFdPB676e4Ve4S', 'USER', 'FALSE','GRATIS', 2, 'https://ui-avatars.com/api/?name=usuario&background=random&color=fff&size=128'),
('prueba1', 'usuario1@correo.com', '$2a$10$dmkVr.E0jsbk5.rq0IxZAe/QdQPsTDXoy3DRo1StFdPB676e4Ve4S', 'USER', 'FALSE','GRATIS', 2, 'https://ui-avatars.com/api/?name=prueba1&background=random&color=fff&size=128'),
('prueba2', 'usuario2@correo.com', '$2a$10$dmkVr.E0jsbk5.rq0IxZAe/QdQPsTDXoy3DRo1StFdPB676e4Ve4S', 'USER', 'FALSE','GRATIS', NULL, 'https://ui-avatars.com/api/?name=prueba2&background=random&color=fff&size=128'),
('prueba3', 'usuario3@correo.com', '$2a$10$dmkVr.E0jsbk5.rq0IxZAe/QdQPsTDXoy3DRo1StFdPB676e4Ve4S', 'USER', 'FALSE','GRATIS', NULL, 'https://ui-avatars.com/api/?name=prueba3&background=random&color=fff&size=128');


INSERT INTO solicitudes (remitente_id, destinatario_id, tipo, estado) VALUES (3, 2, 'ENTRENAMIENTO', 'ACEPTADA');
INSERT INTO solicitudes (remitente_id, destinatario_id, tipo, estado) VALUES (4, 2, 'ENTRENAMIENTO', 'ACEPTADA');
INSERT INTO amistades (usuario1_id, usuario2_id) VALUES (2, 3);
-- =======================================================
-- 2. CATÁLOGO DE EJERCICIOS (Info)
-- =======================================================
-- Código 1 = Fuerza, Código 2 = Cardio
INSERT INTO ejercicio_info (codigo, nombre, descripcion, enlace_explicacion) VALUES 
(1, 'Press Banca con barra', 'Pecho. Barra en banco plano.', 'https://musclewiki.com/es-es/exercise/barbell-bench-press'),
(1, 'Sentadilla con barra', 'Piernas. Barra tras nuca.', 'https://musclewiki.com/es-es/exercise/barbell-squat'),
(1, 'Peso Muerto con barra', 'Espalda baja y cadena posterior.', 'https://musclewiki.com/es-es/exercise/barbell-deadlift'),
(1, 'Dominadas', 'Espalda. Tracción peso corporal.', 'https://musclewiki.com/es-es/exercise/pull-ups'),
(1, 'Press Militar', 'Hombros. Empuje vertical.', 'https://musclewiki.com/es-es/exercise/barbell-overhead-press'),
(1, 'Remo inclinado con Barra', 'Espalda. Tracción horizontal.', 'https://musclewiki.com/es-es/exercise/barbell-bent-over-row'),
(1, 'Curl de Bíceps', 'Brazos. Barra Z o mancuernas.', 'https://musclewiki.com/es-es/exercise/dumbbell-curl'),
(1, 'Extension Tríceps', 'Brazos. Polea alta.', 'https://musclewiki.com/es-es/exercise/cable-rope-pushdown'),
(1, 'Prensa Piernas', 'Piernas. Máquina inclinada.', 'https://musclewiki.com/es-es/exercise/machine-leg-press'),
(1, 'Elevaciones Lat.', 'Hombros. Mancuernas.', 'https://musclewiki.com/es-es/exercise/dumbbell-lateral-raise'),
(2, 'Cinta de Correr', 'Cardio. Running suave o intervalos.', 'https://musclewiki.com/es-es/exercise/treadmill-walk'),
(2, 'Elíptica', 'Cardio. Sin impacto articular.', null),
(2, 'Bicicleta Estát.', 'Cardio. Ciclo indoor.', null),
(2, 'Remo Máquina', 'Cardio. Ergómetro completo.', null);



-- =======================================================
-- 3. RUTINAS (Solo para el usuario normal - ID 3)
-- =======================================================
INSERT INTO rutinas (nombre, descripcion, usuario_id) VALUES 
('Rutina Full Body', 'Entrenamiento de cuerpo completo 3 días', 3),
('Rutina Torso-Pierna', 'Frecuencia 2, ideal intermedios', 3);


-- =======================================================
-- 4. SESIONES (Datos históricos de entrenamiento)
-- =======================================================
-- Sesión asociada a la Rutina 1 del Usuario 3
INSERT INTO sesiones (fecha, rutina_id) VALUES 
('2023-11-01', 1), -- Sesión 1
('2023-11-03', 1); -- Sesión 2


-- =======================================================
-- 5. EJERCICIOS REALIZADOS (Series)
-- =======================================================
-- Ejercicios para la Sesión 1 (Full Body)
INSERT INTO ejercicios (sesion_id, ejercicio_info_id, param1, param2) VALUES
-- Press Banca: 60kg x 10 reps
(1, 1, 60.0, 10.0),
-- Sentadilla: 80kg x 8 reps
(1, 2, 80.0, 8.0),
-- Dominadas: 0kg x 12 reps
(1, 4, 0.0, 12.0),
-- Cinta Correr: 5km x 25 min
(1, 11, 5.0, 25.0);

-- Ejercicios para la Sesión 2
INSERT INTO ejercicios (sesion_id, ejercicio_info_id, param1, param2) VALUES
(2, 3, 100.0, 5.0), -- Peso Muerto
(2, 5, 40.0, 10.0); -- Press Militar


-- =======================================================
-- 6. SINCRONIZACIÓN DE SECUENCIAS
-- =======================================================
-- Le decimos a PostgreSQL que el próximo ID no es el 1, sino el siguiente al último insertado.
SELECT setval('ejercicio_info_ejercicio_info_id_seq', (SELECT MAX(ejercicio_info_id) FROM ejercicio_info));
SELECT setval('rutinas_rutina_id_seq', (SELECT MAX(rutina_id) FROM rutinas));
SELECT setval('sesiones_sesion_id_seq', (SELECT MAX(sesion_id) FROM sesiones));
SELECT setval('ejercicios_ejercicio_id_seq', (SELECT MAX(ejercicio_id) FROM ejercicios));
SELECT setval('usuarios_usuario_id_seq', (SELECT MAX(usuario_id) FROM usuarios));
SELECT setval('solicitudes_id_seq', (SELECT MAX(id) FROM solicitudes) + 1);
SELECT setval('amistades_id_seq', (SELECT MAX(id) FROM amistades) + 1);